"""Cómo se corrige cada regla SAST propia: un ejemplo mínimo antes/después en su lenguaje.

Los ejemplos ilustran el patrón que detecta la regla (rules/*.yml) y su corrección habitual; no son un
parche para el código concreto del hallazgo. Cortos a propósito: se leen en un panel lateral y en un PR.
"""

from __future__ import annotations

# rule_id: (lenguaje para resaltar, antes, después, nota opcional)
EXAMPLES: dict[str, tuple[str, str, str, str]] = {
    # --- Python ---
    "appsec.py.eval-exec-non-literal": ("python", "value = eval(request.args['expr'])",
                                        "import ast\nvalue = ast.literal_eval(request.args['expr'])  # solo literales",
                                        "Si necesitas operaciones, usa una tabla de funciones permitidas en vez de evaluar texto."),
    "appsec.py.shell-command-non-literal": ("python", "subprocess.run(f\"convert {name} out.png\", shell=True)",
                                            "subprocess.run([\"convert\", name, \"out.png\"], check=True)  # sin shell",
                                            "Valida `name` contra una lista permitida o una expresión estricta."),
    "appsec.py.sql-string-building": ("python", "cursor.execute(f\"SELECT * FROM users WHERE id = {user_id}\")",
                                      "cursor.execute(\"SELECT * FROM users WHERE id = %s\", (user_id,))", ""),
    "appsec.py.sql-injection-from-request": ("python", "db.execute(\"SELECT * FROM t WHERE name = '\" + request.args['q'] + \"'\")",
                                             "db.execute(\"SELECT * FROM t WHERE name = %s\", (request.args['q'],))", ""),
    "appsec.py.ssti-render-template-string": ("python", "return render_template_string(\"Hola \" + name)",
                                              "return render_template(\"hola.html\", name=name)  # plantilla fija, dato como variable", ""),
    "appsec.py.pickle-load": ("python", "data = pickle.loads(request.data)",
                              "data = json.loads(request.data)  # formato de datos, no de objetos",
                              "pickle ejecuta código al deserializar: nunca sobre datos que no generaste tú."),
    "appsec.py.yaml-load-unsafe": ("python", "config = yaml.load(text, Loader=yaml.Loader)", "config = yaml.safe_load(text)", ""),
    "appsec.py.flask-debug-true": ("python", "app.run(debug=True)",
                                   "app.run(debug=os.environ.get(\"FLASK_DEBUG\") == \"1\")  # nunca en producción",
                                   "El depurador de Flask permite ejecutar código desde el navegador."),
    "appsec.py.requests-verify-false": ("python", "requests.get(url, verify=False)",
                                        "requests.get(url, timeout=10)  # verifica el certificado (por defecto)",
                                        "Si es una CA interna, pasa su bundle: verify=\"/ruta/ca.pem\"."),
    "appsec.py.jwt-decode-unverified": ("python", "claims = jwt.decode(token, options={\"verify_signature\": False})",
                                        "claims = jwt.decode(token, key, algorithms=[\"RS256\"], audience=AUDIENCE, issuer=ISSUER)", ""),
    "appsec.py.weak-password-hash": ("python", "digest = hashlib.md5(password.encode()).hexdigest()",
                                     "from argon2 import PasswordHasher\ndigest = PasswordHasher().hash(password)",
                                     "Para contraseñas: Argon2id, scrypt o bcrypt, nunca un hash rápido."),
    "appsec.py.django-mark-safe-non-literal": ("python", "return mark_safe(f\"<b>{comment}</b>\")",
                                               "return format_html(\"<b>{}</b>\", comment)  # escapa el dato", ""),
    "appsec.py.path-traversal-from-request": ("python", "return send_file(os.path.join(BASE, request.args['file']))",
                                              "return send_from_directory(BASE, request.args['file'])  # rechaza ../", ""),
    "appsec.py.ssrf-from-request": ("python", "requests.get(request.args['url'])",
                                    "url = request.args['url']\nif urlparse(url).hostname not in ALLOWED_HOSTS:\n    abort(400)\nrequests.get(url, timeout=10, allow_redirects=False)",
                                    "Resuelve el nombre y rechaza direcciones privadas o de metadatos si el destino no es fijo."),
    # --- JavaScript / TypeScript ---
    "appsec.js.eval-non-literal": ("javascript", "const result = eval(req.query.expr)",
                                   "const result = JSON.parse(req.query.data) // datos, no código", ""),
    "appsec.js.command-injection": ("javascript", "exec(`git log ${req.query.branch}`)",
                                    "execFile('git', ['log', '--end-of-options', branch]) // sin shell; branch no puede ser una opción",
                                    "Valida `branch` contra una lista permitida o un patrón estricto."),
    "appsec.js.sql-injection": ("javascript", "db.query(`SELECT * FROM users WHERE id = ${req.params.id}`)",
                                "db.query('SELECT * FROM users WHERE id = $1', [req.params.id])", ""),
    "appsec.js.dom-xss-sink": ("javascript", "element.innerHTML = location.hash.slice(1)",
                               "element.textContent = location.hash.slice(1)", "Si necesitas HTML, sanéalo con DOMPurify."),
    "appsec.js.react-dangerously-set-inner-html": ("javascript", "<div dangerouslySetInnerHTML={{ __html: comment }} />",
                                                   "<div>{comment}</div> // React escapa el texto",
                                                   "Si el HTML es necesario: DOMPurify.sanitize(comment) antes de insertarlo."),
    "appsec.js.path-traversal": ("javascript", "res.sendFile(path.join(BASE, req.query.file))",
                                 "const target = path.resolve(BASE, req.query.file)\nif (!target.startsWith(BASE + path.sep)) return res.sendStatus(400)\nres.sendFile(target)", ""),
    "appsec.js.open-redirect": ("javascript", "res.redirect(req.query.next)",
                                "const next = ALLOWED.has(req.query.next) ? req.query.next : '/'\nres.redirect(next)", ""),
    "appsec.js.jwt-none-algorithm": ("javascript", "jwt.verify(token, key, { algorithms: ['none', 'HS256'] })",
                                     "jwt.verify(token, key, { algorithms: ['RS256'], audience: AUD, issuer: ISS })", ""),
    "appsec.js.jwt-hardcoded-secret": ("javascript", "jwt.sign(payload, 'mi-secreto')",
                                       "jwt.sign(payload, process.env.JWT_SECRET, { expiresIn: '15m' })",
                                       "Rota el secreto que estaba en el código: ya está en el historial."),
    "appsec.js.tls-reject-unauthorized-false": ("javascript", "https.request({ ...options, rejectUnauthorized: false })",
                                                "https.request({ ...options, ca: fs.readFileSync('ca.pem') }) // valida el certificado", ""),
    "appsec.js.weak-hash": ("javascript", "crypto.createHash('md5').update(password)",
                            "await argon2.hash(password) // contraseñas\ncrypto.createHash('sha256') // integridad", ""),
    # --- Java ---
    "appsec.java.sql-concatenation": ("java", "stmt.executeQuery(\"SELECT * FROM users WHERE id = \" + id);",
                                      "PreparedStatement ps = conn.prepareStatement(\"SELECT * FROM users WHERE id = ?\");\nps.setString(1, id);", ""),
    "appsec.java.runtime-exec-concatenation": ("java", "Runtime.getRuntime().exec(\"ping \" + host);",
                                               "new ProcessBuilder(\"ping\", \"-c\", \"1\", host).start(); // sin shell",
                                               "Valida `host` contra una lista permitida."),
    "appsec.java.objectinputstream-readobject": ("java", "Object value = new ObjectInputStream(input).readObject();",
                                                 "ObjectInputStream in = new ObjectInputStream(input);\nin.setObjectInputFilter(ObjectInputFilter.Config.createFilter(\"com.acme.dto.*;!*\"));",
                                                 "Mejor aún: un formato de datos (JSON) en lugar de serialización Java."),
    "appsec.java.xxe-documentbuilder": ("java", "DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();",
                                        "DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();\nfactory.setFeature(\"http://apache.org/xml/features/disallow-doctype-decl\", true);", ""),
    "appsec.java.trust-all-certificates": ("java", "public void checkServerTrusted(X509Certificate[] c, String a) {}",
                                           "// Usa el TrustManager por defecto; para una CA interna, cárgala en un KeyStore propio", ""),
    "appsec.java.hostname-verifier-allow-all": ("java", "connection.setHostnameVerifier((host, session) -> true);",
                                                "// Quita el HostnameVerifier propio: el predeterminado comprueba el nombre", ""),
    "appsec.java.weak-cipher": ("java", "Cipher.getInstance(\"DES/ECB/PKCS5Padding\")", "Cipher.getInstance(\"AES/GCM/NoPadding\")", ""),
    "appsec.java.hardcoded-password": ("java", "String password = \"S3cr3t!\";", "String password = System.getenv(\"DB_PASSWORD\");",
                                       "Rota la contraseña: ya está en el historial del repositorio."),
    "appsec.java.spring-csrf-disabled": ("java", "http.csrf(csrf -> csrf.disable());",
                                         "http.csrf(Customizer.withDefaults()); // desactívalo solo en APIs sin cookies de sesión", ""),
    # --- C# ---
    "appsec.cs.sql-string-building": ("csharp", "new SqlCommand(\"SELECT * FROM Users WHERE Id = \" + id, conn);",
                                      "var cmd = new SqlCommand(\"SELECT * FROM Users WHERE Id = @id\", conn);\ncmd.Parameters.AddWithValue(\"@id\", id);", ""),
    "appsec.cs.process-start-concatenation": ("csharp", "Process.Start(\"cmd.exe\", \"/c ping \" + host);",
                                              "var info = new ProcessStartInfo(\"ping\") { UseShellExecute = false };\ninfo.ArgumentList.Add(host);\nProcess.Start(info);", ""),
    "appsec.cs.insecure-deserialization": ("csharp", "new BinaryFormatter().Deserialize(stream);",
                                           "JsonSerializer.Deserialize<OrderDto>(stream);", "BinaryFormatter está obsoleto y no es seguro."),
    "appsec.cs.certificate-validation-bypass": ("csharp", "handler.ServerCertificateCustomValidationCallback = (m, c, ch, e) => true;",
                                                "// Quita el callback: la validación predeterminada comprueba cadena y nombre", ""),
    "appsec.cs.razor-html-raw-non-literal": ("csharp", "@Html.Raw(Model.Comment)", "@Model.Comment @* Razor escapa el texto *@", ""),
    "appsec.cs.weak-hash": ("csharp", "MD5.HashData(Encoding.UTF8.GetBytes(password));",
                            "var hash = new PasswordHasher<User>().HashPassword(user, password);", ""),
    # --- Go ---
    "appsec.go.sql-string-building": ("go", "db.Query(\"SELECT * FROM users WHERE id = \" + id)", "db.Query(\"SELECT * FROM users WHERE id = $1\", id)", ""),
    "appsec.go.shell-command-non-literal": ("go", "exec.Command(\"sh\", \"-c\", \"ping \"+host)", "exec.Command(\"ping\", \"-c\", \"1\", host) // sin shell", ""),
    "appsec.go.tls-insecure-skip-verify": ("go", "&tls.Config{InsecureSkipVerify: true}", "&tls.Config{RootCAs: pool, MinVersion: tls.VersionTLS12}", ""),
    "appsec.go.template-html-unescaped": ("go", "template.HTML(userInput)", "userInput // html/template lo escapa al pintarlo", ""),
    "appsec.go.path-traversal-from-request": ("go", "http.ServeFile(w, r, filepath.Join(base, r.URL.Query().Get(\"file\")))",
                                              "root, _ := os.OpenRoot(base) // Go 1.24+: no permite salir de base\nf, err := root.Open(r.URL.Query().Get(\"file\"))", ""),
    "appsec.go.weak-hash": ("go", "md5.Sum([]byte(password))", "bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)", ""),
    # --- PHP ---
    "appsec.php.sql-injection": ("php", "$db->query(\"SELECT * FROM users WHERE id = \" . $_GET['id']);",
                                 "$stmt = $db->prepare('SELECT * FROM users WHERE id = ?');\n$stmt->execute([$_GET['id']]);", ""),
    "appsec.php.command-injection": ("php", "system('ping ' . $_GET['host']);", "system('ping -c 1 ' . escapeshellarg($host));",
                                     "Mejor: valida $host contra una lista permitida antes."),
    "appsec.php.eval-non-literal": ("php", "eval($_POST['code']);", "// Elimina eval: usa una tabla de operaciones permitidas", ""),
    "appsec.php.unserialize-from-request": ("php", "$data = unserialize($_COOKIE['cart']);", "$data = json_decode($_COOKIE['cart'], true);", ""),
    "appsec.php.file-inclusion-from-request": ("php", "include $_GET['page'] . '.php';",
                                               "$pages = ['home' => 'home.php', 'about' => 'about.php'];\ninclude $pages[$_GET['page']] ?? 'home.php';", ""),
    "appsec.php.reflected-xss": ("php", "echo $_GET['name'];", "echo htmlspecialchars($_GET['name'], ENT_QUOTES, 'UTF-8');", ""),
    # --- Ruby ---
    "appsec.rb.sql-interpolation": ("ruby", "User.where(\"email = '#{params[:email]}'\")", "User.where(email: params[:email])", ""),
    "appsec.rb.command-injection": ("ruby", "system(\"convert #{params[:file]} out.png\")", "system(\"convert\", params[:file], \"out.png\") # sin shell", ""),
    "appsec.rb.unsafe-deserialization": ("ruby", "Marshal.load(Base64.decode64(params[:data]))", "JSON.parse(params[:data])", ""),
    "appsec.rb.html-safe-non-literal": ("ruby", "comment.html_safe", "sanitize(comment) # o simplemente <%= comment %>, que escapa", ""),
    "appsec.rb.mass-assignment-permit-all": ("ruby", "User.update(params[:user].permit!)", "User.update(params.require(:user).permit(:name, :email))", ""),
    "appsec.rb.open-redirect": ("ruby", "redirect_to params[:next]", "redirect_to(params[:next].presence_in(ALLOWED_PATHS) || root_path)", ""),
}
