/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cve-db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_cve_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cve-db/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_cve_db_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cve-db/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Item */
        get: operations["item_api_cve_db_item_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cve-db/affected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Affected
         * @description Your repositories with a finding that cites this CVE (open or fixed), one page at a time.
         */
        get: operations["affected_api_cve_db_affected_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Policy
         * @description Anyone can read them (they explain due dates); an administrator changes them.
         */
        get: operations["policy_api_sla_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/cra": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cra Policy
         * @description Anyone can read it (the panel shows or hides the CRA kit with it); an administrator changes it.
         */
        get: operations["cra_policy_api_policies_cra_get"];
        put?: never;
        /**
         * Set Cra Policy
         * @description Turns the CRA kit on or off, with a reason kept in the history. Off keeps products and decisions.
         */
        post: operations["set_cra_policy_api_policies_cra_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cra": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_cra_get"];
        put?: never;
        /**
         * Change
         * @description Marks products, records the assessment of an event (only "exploited in our product" starts the clocks) and
         *     which stages were sent. Answers the new overview.
         */
        post: operations["change_api_cra_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cra/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products */
        get: operations["products_api_cra_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cra/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Most urgent first. The ENISA draft is only built for the exploited events on the page.
         */
        get: operations["events_api_cra_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cra/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Assets
         * @description Analyzed assets that can still be marked as products, filtered by name.
         */
        get: operations["assets_api_cra_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence Overview */
        get: operations["evidence_overview_api_evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evidence Assets
         * @description The asset picker: analyzed assets by name, with whether each has what an SBOM needs.
         */
        get: operations["evidence_assets_api_evidence_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Portfolio Evidence
         * @description Consolidated audit evidence of every analyzed asset (open, fixed and exceptions), for one framework.
         */
        post: operations["portfolio_evidence_api_evidence_portfolio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/portfolio/sbom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio Sbom
         * @description One CycloneDX document: each asset a top-level component with its packages. `organization` names the portfolio.
         */
        get: operations["portfolio_sbom_api_evidence_portfolio_sbom_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/portfolio/vex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio Vex
         * @description One OpenVEX document with the statements of the same assets as the portfolio SBOM.
         */
        get: operations["portfolio_vex_api_evidence_portfolio_vex_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pull-requests/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Target Branches
         * @description Branches whose PRs are reviewed; an empty list means the repository's default branch.
         */
        post: operations["target_branches_api_pull_requests_branches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pull-requests/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Now
         * @description Reviews (or reviews again) a pull request's head commit now, whether the repository is watched or not.
         */
        post: operations["review_now_api_pull_requests_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/branch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Branch
         * @description Sets the branch every platform scan of this repository reads; null goes back to the default branch.
         */
        post: operations["scan_branch_api_repositories_branch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/secrets/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config
         * @description What secret detection applies to every repository scan; only admins see (and change) the patterns.
         */
        get: operations["config_api_secrets_config_get"];
        put?: never;
        /**
         * Save Config
         * @description Replaces the settings; takes effect from the next scan. A reason is required and kept in the history.
         */
        post: operations["save_config_api_secrets_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Asset Config
         * @description A repository's own secret detection entries (empty: it uses the defaults as they are).
         */
        get: operations["asset_config_api_assets_secrets_get"];
        put?: never;
        /**
         * Save Asset Config
         * @description Replaces a repository's own entries; they add to the defaults from its next scan. A reason is required.
         */
        post: operations["save_asset_config_api_assets_secrets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/secrets/builtin-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Builtin Rules
         * @description Gitleaks' default rules (what can be turned off), with the Trivy rule that is turned off with each, if any.
         */
        get: operations["builtin_rules_api_secrets_builtin_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AffectedAsset */
        AffectedAsset: {
            /** Asset */
            asset: string;
            /** Name */
            name: string;
            /** Open */
            open: number;
            /** Fixed */
            fixed: number;
            /** Packages */
            packages: string[];
        };
        /** AffectedAssetPage */
        AffectedAssetPage: {
            /** Items */
            items: components["schemas"]["AffectedAsset"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** AssessIn */
        AssessIn: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "assess";
            /** Event */
            event: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "not_affected" | "exploited";
            /** Reason */
            reason?: string | null;
        };
        /**
         * AssetSecretConfig
         * @description A repository's own entries, added to the defaults (`defaults` counts them) in its scans.
         */
        AssetSecretConfig: {
            allowlist: components["schemas"]["SecretAllowlistView"];
            /** Rules */
            rules: components["schemas"]["SecretRuleView"][];
            /** Disabled Rules */
            disabled_rules: string[];
            /** Reason */
            reason: string | null;
            /** By */
            by: string | null;
            /** At */
            at: string | null;
            /** History */
            history: components["schemas"]["SecretHistoryEntry"][];
            limits: components["schemas"]["SecretLimits"];
            /** Key */
            key: string;
            defaults: components["schemas"]["SecretCounts"];
        };
        /** AssetSecretConfigIn */
        AssetSecretConfigIn: {
            allowlist: components["schemas"]["SecretAllowlist"];
            /** Rules */
            rules: components["schemas"]["SecretRule"][];
            /** Disabled Rules */
            disabled_rules: string[];
            /** Reason */
            reason: string;
            /** Key */
            key: string;
        };
        /** BuiltinRule */
        BuiltinRule: {
            /** Id */
            id: string;
            /** Trivy */
            trivy: string | null;
        };
        /** BuiltinRules */
        BuiltinRules: {
            /** Engine */
            engine: string;
            /** Version */
            version: string;
            /** Rules */
            rules: components["schemas"]["BuiltinRule"][];
        };
        /** CraAssessment */
        CraAssessment: {
            /** By */
            by: string | null;
            /** At */
            at: string | null;
            /** Reason */
            reason: string | null;
            /** Legacy */
            legacy: boolean;
        };
        /** CraAsset */
        CraAsset: {
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /** CraAssetPage */
        CraAssetPage: {
            /** Items */
            items: components["schemas"]["CraAsset"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** CraCounts */
        CraCounts: {
            /** Products */
            products: number;
            /** Unscanned */
            unscanned: number;
            /** Events */
            events: number;
            /** Pending */
            pending: number;
            /** To Assess */
            to_assess: number;
            /** Assets */
            assets: number;
            /** Candidates */
            candidates: number;
        };
        /** CraEvent */
        CraEvent: {
            /** Id */
            id: string;
            /** Asset */
            asset: string;
            /** Product */
            product: string;
            /** Support Until */
            support_until: string | null;
            /** Cve */
            cve: string;
            /** Title */
            title: string | null;
            /** Severity */
            severity: string | null;
            /** Packages */
            packages: string[];
            kev: components["schemas"]["CraKev"];
            /** Signal At */
            signal_at: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "to_assess" | "not_affected" | "exploited";
            assessment: components["schemas"]["CraAssessment"] | null;
            /** Aware At */
            aware_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "fixed";
            /** Fixed At */
            fixed_at: string | null;
            /** Stages */
            stages: components["schemas"]["CraStage"][];
            /** Done */
            done: boolean;
            /** Draft */
            draft: string | null;
        };
        /** CraEventPage */
        CraEventPage: {
            /** Items */
            items: components["schemas"]["CraEvent"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** CraKev */
        CraKev: {
            /** Date Added */
            date_added: string | null;
            /** Ransomware */
            ransomware: boolean;
            /** Name */
            name: string | null;
        };
        /** CraOverview */
        CraOverview: {
            /** Reporting Page */
            reporting_page: string;
            counts: components["schemas"]["CraCounts"];
        };
        /** CraPolicy */
        CraPolicy: {
            /** Enabled */
            enabled: boolean;
            /** By */
            by: string | null;
            /** At */
            at: string | null;
            /** Reason */
            reason: string | null;
            /** History */
            history: components["schemas"]["CraPolicyChange"][];
        };
        /** CraPolicyChange */
        CraPolicyChange: {
            /** Enabled */
            enabled: boolean;
            /** By */
            by: string | null;
            /** At */
            at: string | null;
            /** Reason */
            reason: string | null;
        };
        /** CraPolicyIn */
        CraPolicyIn: {
            /** Enabled */
            enabled: boolean;
            /** Reason */
            reason: string;
        };
        /** CraProduct */
        CraProduct: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Asset */
            asset: string;
            /** Support Until */
            support_until: string | null;
            /** Last Complete */
            last_complete: string | null;
            /** By */
            by?: string | null;
            /** At */
            at?: string | null;
        };
        /** CraProductPage */
        CraProductPage: {
            /** Items */
            items: components["schemas"]["CraProduct"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** CraStage */
        CraStage: {
            /**
             * Id
             * @enum {string}
             */
            id: "early_warning" | "notification" | "final_report";
            /** Label */
            label: string;
            /** Due */
            due: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "overdue" | "pending" | "waiting" | "sent";
            /** Sent */
            sent: {
                [key: string]: string;
            } | null;
        };
        /** CveDetail */
        CveDetail: {
            /** Id */
            id: string;
            /** Published */
            published: string | null;
            /** Severity */
            severity: string | null;
            /** Score */
            score: number | null;
            /** Version */
            version: string | null;
            /** Description */
            description: string;
            /** Status */
            status?: string | null;
            /** Kev */
            kev: boolean;
            /** Epss */
            epss: number | null;
            /** Epss Percentile */
            epss_percentile: number | null;
            /**
             * Affects
             * @default false
             */
            affects: boolean;
            /** Vector */
            vector: string | null;
            /** Modified */
            modified: string | null;
            /** Cwe */
            cwe: string[];
            /** References */
            references: {
                [key: string]: unknown;
            }[];
            /** Kev Detail */
            kev_detail: {
                [key: string]: unknown;
            } | null;
            /** Score Source */
            score_source: string | null;
            euvd: components["schemas"]["Euvd"] | null;
        };
        /** CvePage */
        CvePage: {
            /** Items */
            items: components["schemas"]["CveRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Mine Total */
            mine_total: number;
        };
        /** CveRow */
        CveRow: {
            /** Id */
            id: string;
            /** Published */
            published: string | null;
            /** Severity */
            severity: string | null;
            /** Score */
            score: number | null;
            /** Version */
            version: string | null;
            /** Description */
            description: string;
            /** Status */
            status?: string | null;
            /** Kev */
            kev: boolean;
            /** Epss */
            epss: number | null;
            /** Epss Percentile */
            epss_percentile: number | null;
            /**
             * Affects
             * @default false
             */
            affects: boolean;
        };
        /** Dashboard */
        Dashboard: {
            /** Window Days */
            window_days: number;
            /** Generated At */
            generated_at: string;
            /** Kpis */
            kpis: {
                [key: string]: unknown;
            };
            /** Issues Over Time */
            issues_over_time: {
                [key: string]: unknown;
            }[];
            /** Open Vs Fixed */
            open_vs_fixed: {
                [key: string]: unknown;
            }[];
            /** Top Assets */
            top_assets: {
                [key: string]: unknown;
            }[];
            /** By Cwe */
            by_cwe: {
                [key: string]: unknown;
            }[];
            /** Exploitability */
            exploitability: {
                [key: string]: unknown;
            };
            /** Activity */
            activity: {
                [key: string]: unknown;
            }[];
            /** Recent Runs */
            recent_runs: {
                [key: string]: unknown;
            }[];
            /** Top Issues */
            top_issues: {
                [key: string]: unknown;
            }[];
            /** Kev News */
            kev_news: {
                [key: string]: unknown;
            };
            /** Cve News */
            cve_news: {
                [key: string]: unknown;
            };
            /** Tools */
            tools: {
                [key: string]: unknown;
            }[];
        };
        /** Euvd */
        Euvd: {
            /** Id */
            id: string;
            /** Url */
            url: string | null;
            /** Score */
            score: number | null;
            /** Version */
            version: string | null;
            /** Vector */
            vector: string | null;
            /** Severity */
            severity: string | null;
            /** Exploited Since */
            exploited_since: string | null;
            /** Published */
            published: string | null;
        };
        /** EvidenceAsset */
        EvidenceAsset: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "repository" | "image";
            /** Last Complete */
            last_complete: string | null;
            /** Sbom */
            sbom: boolean;
        };
        /** EvidenceAssetPage */
        EvidenceAssetPage: {
            /** Items */
            items: components["schemas"]["EvidenceAsset"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** EvidenceOverview */
        EvidenceOverview: {
            /** Assets */
            assets: number;
            /** Complete */
            complete: number;
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Docker */
            docker?: boolean | null;
            /** Workers */
            workers?: number | null;
            /** Queued */
            queued?: number | null;
        };
        /** MarkIn */
        MarkIn: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "mark";
            /** Event */
            event: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "early_warning" | "notification" | "final_report";
            /** Sent */
            sent: boolean;
        };
        /** PortfolioEvidenceIn */
        PortfolioEvidenceIn: {
            /**
             * Framework
             * @enum {string}
             */
            framework: "soc2" | "iso27001" | "pci" | "cra" | "br-cmn" | "cl-21663" | "co-sfc" | "general";
        };
        /** ProductIn */
        ProductIn: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "product";
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Support Until */
            support_until: string | null;
        };
        /** QueuedRun */
        QueuedRun: {
            /** Id */
            id: string;
            /** Status */
            status: string;
        };
        /** ReopenIn */
        ReopenIn: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "reopen";
            /** Event */
            event: string;
        };
        /** ReviewIn */
        ReviewIn: {
            /** Source Id */
            source_id: string;
            /** Number */
            number: number;
        };
        /** ReviewQueued */
        ReviewQueued: {
            run: components["schemas"]["QueuedRun"];
        };
        /** ScanBranch */
        ScanBranch: {
            /** Uid */
            uid: string;
            /** Branch */
            branch: string | null;
            /** Head Sha */
            head_sha: string | null;
            /** Default Branch */
            default_branch: string | null;
        };
        /** ScanBranchIn */
        ScanBranchIn: {
            /** Uid */
            uid: string;
            /** Branch */
            branch: string | null;
        };
        /**
         * SecretAllowlist
         * @description Regexes are matched against the detected secret; paths are globs relative to the repository root.
         */
        SecretAllowlist: {
            /** Regexes */
            regexes?: string[];
            /** Paths */
            paths?: string[];
            /** Stopwords */
            stopwords?: string[];
        };
        /** SecretAllowlistView */
        SecretAllowlistView: {
            /** Regexes */
            regexes: string[];
            /** Paths */
            paths: string[];
            /** Stopwords */
            stopwords: string[];
        };
        /** SecretConfig */
        SecretConfig: {
            allowlist: components["schemas"]["SecretAllowlistView"];
            /** Rules */
            rules: components["schemas"]["SecretRuleView"][];
            /** Disabled Rules */
            disabled_rules: string[];
            /** Reason */
            reason: string | null;
            /** By */
            by: string | null;
            /** At */
            at: string | null;
            /** History */
            history: components["schemas"]["SecretHistoryEntry"][];
            limits: components["schemas"]["SecretLimits"];
        };
        /** SecretConfigIn */
        SecretConfigIn: {
            allowlist: components["schemas"]["SecretAllowlist"];
            /** Rules */
            rules: components["schemas"]["SecretRule"][];
            /** Disabled Rules */
            disabled_rules: string[];
            /** Reason */
            reason: string;
        };
        /** SecretCounts */
        SecretCounts: {
            /** Rules */
            rules: number;
            /** Disabled */
            disabled: number;
            /** Allowlist */
            allowlist: number;
        };
        /** SecretHistoryEntry */
        SecretHistoryEntry: {
            /** At */
            at: string;
            /** By */
            by: string;
            /** Reason */
            reason: string | null;
            /** Changes */
            changes?: {
                [key: string]: {
                    [key: string]: string[];
                };
            };
        };
        /** SecretLimits */
        SecretLimits: {
            /** Rules */
            rules: number;
            /** Entries */
            entries: number;
            /** Regex */
            regex: number;
            /** Description */
            description: number;
            /** Keywords */
            keywords: number;
        };
        /** SecretRule */
        SecretRule: {
            /** Id */
            id: string;
            /** Description */
            description: string;
            /** Regex */
            regex: string;
            /** Keywords */
            keywords?: string[];
        };
        /** SecretRuleView */
        SecretRuleView: {
            /** Id */
            id: string;
            /** Description */
            description: string;
            /** Regex */
            regex: string;
            /** Keywords */
            keywords: string[];
        };
        /**
         * SlaDays
         * @description Days per severity; null means that severity has no due date.
         */
        SlaDays: {
            /** Critical */
            critical: number | null;
            /** High */
            high: number | null;
            /** Medium */
            medium: number | null;
            /** Low */
            low: number | null;
        };
        /** SlaDefaults */
        SlaDefaults: {
            /** Critical */
            critical: number;
            /** High */
            high: number;
            /** Medium */
            medium: number;
            /** Low */
            low: number;
        };
        /** SlaPolicy */
        SlaPolicy: {
            days: components["schemas"]["SlaDays"];
            defaults: components["schemas"]["SlaDefaults"];
            /** Updated By */
            updated_by: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** TargetBranches */
        TargetBranches: {
            /** Uid */
            uid: string;
            /** Base Branches */
            base_branches: string[];
            /** Default Branch */
            default_branch: string | null;
        };
        /** TargetBranchesIn */
        TargetBranchesIn: {
            /** Uid */
            uid: string;
            /** Branches */
            branches: string[];
        };
        /** UnproductIn */
        UnproductIn: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "unproduct";
            /** Key */
            key: string;
        };
        /** Error */
        Error: {
            /**
             * Error
             * @description In the reader's language.
             */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: {
                days?: number;
                tz?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    search_api_cve_db_get: {
        parameters: {
            query?: {
                q?: string;
                severity?: string | null;
                sort?: string;
                year?: number | null;
                limit?: number;
                offset?: number;
                kev?: string | null;
                mine?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CvePage"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    overview_api_cve_db_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    item_api_cve_db_item_get: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CveDetail"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    affected_api_cve_db_affected_get: {
        parameters: {
            query?: {
                id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AffectedAssetPage"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    policy_api_sla_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlaPolicy"];
                };
            };
        };
    };
    cra_policy_api_policies_cra_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraPolicy"];
                };
            };
        };
    };
    set_cra_policy_api_policies_cra_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CraPolicyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraPolicy"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    overview_api_cra_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraOverview"];
                };
            };
        };
    };
    change_api_cra_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductIn"] | components["schemas"]["UnproductIn"] | components["schemas"]["MarkIn"] | components["schemas"]["AssessIn"] | components["schemas"]["ReopenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraOverview"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    products_api_cra_products_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraProductPage"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    events_api_cra_events_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraEventPage"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    assets_api_cra_assets_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraAssetPage"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    evidence_overview_api_evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOverview"];
                };
            };
        };
    };
    evidence_assets_api_evidence_assets_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceAssetPage"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    portfolio_evidence_api_evidence_portfolio_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioEvidenceIn"];
            };
        };
        responses: {
            /** @description Audit evidence (PDF) of every analyzed asset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    portfolio_sbom_api_evidence_portfolio_sbom_get: {
        parameters: {
            query?: {
                organization?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CycloneDX SBOM of every asset with a completed full scan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.cyclonedx+json": string;
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    portfolio_vex_api_evidence_portfolio_vex_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenVEX statements of every asset with a completed full scan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    target_branches_api_pull_requests_branches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetBranchesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetBranches"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    review_now_api_pull_requests_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueued"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    scan_branch_api_repositories_branch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanBranchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanBranch"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    config_api_secrets_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretConfig"];
                };
            };
        };
    };
    save_config_api_secrets_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretConfig"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    asset_config_api_assets_secrets_get: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetSecretConfig"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    save_asset_config_api_assets_secrets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetSecretConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetSecretConfig"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    builtin_rules_api_secrets_builtin_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuiltinRules"];
                };
            };
        };
    };
}
