/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cve-db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_cve_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cve-db/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_cve_db_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cve-db/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Item */
        get: operations["item_api_cve_db_item_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Policy
         * @description Los ve cualquiera (explican las fechas límite); los cambia un administrador.
         */
        get: operations["policy_api_sla_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cra": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description Lo ve cualquier sesión (el equipo necesita saber qué vence); solo un administrador lo cambia.
         */
        get: operations["overview_api_cra_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AffectedAsset */
        AffectedAsset: {
            /** Asset */
            asset: string;
            /** Name */
            name: string;
            /** Open */
            open: number;
            /** Fixed */
            fixed: number;
            /** Packages */
            packages: string[];
        };
        /** CraAsset */
        CraAsset: {
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /** CraEvent */
        CraEvent: {
            /** Id */
            id: string;
            /** Asset */
            asset: string;
            /** Product */
            product: string;
            /** Support Until */
            support_until: string | null;
            /** Cve */
            cve: string;
            /** Title */
            title: string | null;
            /** Severity */
            severity: string | null;
            /** Packages */
            packages: string[];
            /** Kev */
            kev: {
                [key: string]: unknown;
            };
            /** Aware At */
            aware_at: string | null;
            /** Status */
            status: string;
            /** Fixed At */
            fixed_at: string | null;
            /** Stages */
            stages: components["schemas"]["CraStage"][];
            /** Done */
            done: boolean;
            /** Draft */
            draft: string;
        };
        /** CraOverview */
        CraOverview: {
            /** Products */
            products: components["schemas"]["CraProduct"][];
            /** Events */
            events: components["schemas"]["CraEvent"][];
            /** Assets */
            assets: components["schemas"]["CraAsset"][];
            /** Reporting Page */
            reporting_page: string;
        };
        /** CraProduct */
        CraProduct: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Asset */
            asset: string;
            /** Support Until */
            support_until: string | null;
            /** Last Complete */
            last_complete: string | null;
            /** By */
            by?: string | null;
            /** At */
            at?: string | null;
        };
        /** CraStage */
        CraStage: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Due */
            due: string | null;
            /** State */
            state: string;
            /** Sent */
            sent: {
                [key: string]: string;
            } | null;
        };
        /** CveDetail */
        CveDetail: {
            /** Id */
            id: string;
            /** Published */
            published: string | null;
            /** Severity */
            severity: string | null;
            /** Score */
            score: number | null;
            /** Version */
            version: string | null;
            /** Description */
            description: string;
            /** Status */
            status?: string | null;
            /** Kev */
            kev: boolean;
            /** Epss */
            epss: number | null;
            /** Epss Percentile */
            epss_percentile: number | null;
            /**
             * Affects
             * @default false
             */
            affects: boolean;
            /** Vector */
            vector: string | null;
            /** Modified */
            modified: string | null;
            /** Cwe */
            cwe: string[];
            /** References */
            references: {
                [key: string]: unknown;
            }[];
            /** Kev Detail */
            kev_detail: {
                [key: string]: unknown;
            } | null;
            /** Score Source */
            score_source: string | null;
            euvd: components["schemas"]["Euvd"] | null;
            /** Affected */
            affected: components["schemas"]["AffectedAsset"][];
        };
        /** CvePage */
        CvePage: {
            /** Items */
            items: components["schemas"]["CveRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Mine Total */
            mine_total: number;
        };
        /** CveRow */
        CveRow: {
            /** Id */
            id: string;
            /** Published */
            published: string | null;
            /** Severity */
            severity: string | null;
            /** Score */
            score: number | null;
            /** Version */
            version: string | null;
            /** Description */
            description: string;
            /** Status */
            status?: string | null;
            /** Kev */
            kev: boolean;
            /** Epss */
            epss: number | null;
            /** Epss Percentile */
            epss_percentile: number | null;
            /**
             * Affects
             * @default false
             */
            affects: boolean;
        };
        /** Dashboard */
        Dashboard: {
            /** Window Days */
            window_days: number;
            /** Generated At */
            generated_at: string;
            /** Kpis */
            kpis: {
                [key: string]: unknown;
            };
            /** Issues Over Time */
            issues_over_time: {
                [key: string]: unknown;
            }[];
            /** Open Vs Fixed */
            open_vs_fixed: {
                [key: string]: unknown;
            }[];
            /** Top Assets */
            top_assets: {
                [key: string]: unknown;
            }[];
            /** By Cwe */
            by_cwe: {
                [key: string]: unknown;
            }[];
            /** Exploitability */
            exploitability: {
                [key: string]: unknown;
            };
            /** Activity */
            activity: {
                [key: string]: unknown;
            }[];
            /** Recent Runs */
            recent_runs: {
                [key: string]: unknown;
            }[];
            /** Top Issues */
            top_issues: {
                [key: string]: unknown;
            }[];
            /** Kev News */
            kev_news: {
                [key: string]: unknown;
            };
            /** Cve News */
            cve_news: {
                [key: string]: unknown;
            };
            /** Tools */
            tools: {
                [key: string]: unknown;
            }[];
        };
        /** Euvd */
        Euvd: {
            /** Id */
            id: string;
            /** Url */
            url: string | null;
            /** Score */
            score: number | null;
            /** Version */
            version: string | null;
            /** Vector */
            vector: string | null;
            /** Severity */
            severity: string | null;
            /** Exploited Since */
            exploited_since: string | null;
            /** Published */
            published: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Docker */
            docker?: boolean | null;
            /** Queued */
            queued?: number | null;
        };
        /**
         * SlaDays
         * @description Días por severidad; None = esa severidad no vence.
         */
        SlaDays: {
            /** Critical */
            critical: number | null;
            /** High */
            high: number | null;
            /** Medium */
            medium: number | null;
            /** Low */
            low: number | null;
        };
        /** SlaDefaults */
        SlaDefaults: {
            /** Critical */
            critical: number;
            /** High */
            high: number;
            /** Medium */
            medium: number;
            /** Low */
            low: number;
        };
        /** SlaPolicy */
        SlaPolicy: {
            days: components["schemas"]["SlaDays"];
            defaults: components["schemas"]["SlaDefaults"];
            /** Updated By */
            updated_by: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: {
                days?: 7 | 30 | 90 | 365;
                tz?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_cve_db_get: {
        parameters: {
            query?: {
                q?: string;
                severity?: string | null;
                sort?: string;
                year?: number | null;
                limit?: number;
                offset?: number;
                kev?: string | null;
                mine?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CvePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_cve_db_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    item_api_cve_db_item_get: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CveDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    policy_api_sla_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlaPolicy"];
                };
            };
        };
    };
    overview_api_cra_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraOverview"];
                };
            };
        };
    };
}
